"""add_custom_tag_categories

Revision ID: 828ca5263985
Revises: 914e38623288
Create Date: 2026-08-05 20:17:22.156747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '828ca5263985'
down_revision: Union[str, None] = '914e38623288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'name', name='uq_tag_category_campaign_name')
    )
    op.add_column('tags', sa.Column('custom_category_id', sa.UUID(), nullable=True))
    op.alter_column('tags', 'tag_type',
               existing_type=postgresql.ENUM('character', 'location', 'item', 'quest', 'faction', name='tagtype'),
               nullable=True)
    op.create_foreign_key(None, 'tags', 'tag_categories', ['custom_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.alter_column('tags', 'tag_type',
               existing_type=postgresql.ENUM('character', 'location', 'item', 'quest', 'faction', name='tagtype'),
               nullable=False)
    op.drop_column('tags', 'custom_category_id')
    op.drop_table('tag_categories')
    # ### end Alembic commands ###
