"""add_user_avatar

Revision ID: eb3bb3b53bd9
Revises: 00bc84d5d90c
Create Date: 2026-06-05 20:30:26.970553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3bb3b53bd9'
down_revision: Union[str, None] = '00bc84d5d90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_data')
    # ### end Alembic commands ###
